//-------------------------------------------------------
// Autogenerated from 'alarmcar.vmf'
//-------------------------------------------------------
AlarmCar <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.Admin_caralarm_car1,
			EntityGroup.SpawnTables.Admin_caralarm_glass1,
			EntityGroup.SpawnTables.Admin_caralarm_light1,
			EntityGroup.SpawnTables.Admin_caralarm_light11,
			EntityGroup.SpawnTables.Admin_caralarm_light12,
			EntityGroup.SpawnTables.Admin_caralarm_light13,
			EntityGroup.SpawnTables.Admin_caralarm_glass1_off,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.Admin_carchirp1,
			EntityGroup.SpawnTables.Admin_remark_caralarm,
			EntityGroup.SpawnTables.Admin_caralarm_car1,
			EntityGroup.SpawnTables.Admin_alarmtimer1,
			EntityGroup.SpawnTables.Admin_caralarm1,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.Admin_branch_caralarm,
			EntityGroup.SpawnTables.Admin_caralarm_glass1,
			EntityGroup.SpawnTables.Admin_relay_caralarm_off,
			EntityGroup.SpawnTables.Admin_caralarm_glass1_off,
			EntityGroup.SpawnTables.Admin_case_car_color,
			EntityGroup.SpawnTables.Admin_relay_caralarm_on,
			EntityGroup.SpawnTables.Admin_caralarm_headlights11,
			EntityGroup.SpawnTables.Admin_caralarm_headlights1,
			EntityGroup.SpawnTables.Admin_caralarm_light13,
			EntityGroup.SpawnTables.Admin_caralarm_light12,
			EntityGroup.SpawnTables.Admin_caralarm_light11,
			EntityGroup.SpawnTables.Admin_caralarm_light1,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			Admin_branch_caralarm = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					angles = Vector( -0, -60, 0 )
					InitialValue = "$start_off"
					spawnflags = "0"
					targetname = "Admin_branch_caralarm"
					origin = Vector( 5.84983, -24.6707, 91.2375 )
					connections =
					{
						OnFalse =
						{
							cmd1 = "Admin_relay_caralarm_onTrigger0-1"
						}
						OnTrue =
						{
							cmd1 = "Admin_relay_caralarm_offTrigger0-1"
						}
					}
				}
			}
			Admin_relay_caralarm_off = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					angles = Vector( -0, -60, 0 )
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "Admin_relay_caralarm_off"
					origin = Vector( -26.1477, -24.6721, 59.2375 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "Admin_caralarm_game_eventKill0-1"
							cmd2 = "Admin_caralarm_car1Disable0-1"
							cmd3 = "Admin_relay_caralarm_onEnable0.02-1"
							cmd4 = "Admin_relay_caralarm_offDisable0.02-1"
							cmd5 = "Admin_remark_caralarmKill0-1"
							cmd6 = "Admin_caralarm_glass1_offEnable0-1"
							cmd7 = "Admin_caralarm_glass1Disable0-1"
							cmd8 = "Admin_caralarm_headlights1LightOff0-1"
							cmd9 = "Admin_caralarm_light1HideSprite0-1"
						}
					}
				}
			}
			Admin_relay_caralarm_on = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					angles = Vector( -0, -60, 0 )
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "Admin_relay_caralarm_on"
					origin = Vector( 5.84983, -24.6707, 59.2375 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "Admin_maker_alarm_onForceSpawn0.01-1"
							cmd2 = "Admin_caralarm_car1Enable0-1"
							cmd3 = "Admin_relay_caralarm_onDisable0.02-1"
							cmd4 = "Admin_relay_caralarm_offEnable0.02-1"
							cmd5 = "Admin_caralarm_glass1Enable0-1"
							cmd6 = "Admin_caralarm_glass1_offDisable0-1"
						}
					}
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					angles = Vector( -0, -60, 0 )
					spawnflags = "1"
					origin = Vector( 5.84853, -40.6729, 59.2375 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "Admin_branch_caralarmTest0.1-1"
						}
					}
				}
			}
			Admin_caralarm1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					angles = Vector( -0, -60, 0 )
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "Car.Alarm"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "4000"
					SourceEntityName = "Admin_caralarm_car1"
					spawnflags = "16"
					spindown = "0"
					spinup = "0"
					targetname = "Admin_caralarm1"
					volstart = "0"
					origin = Vector( -30.1483, -16.6813, 18.3265 )
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					angles = Vector( -0, -60, 0 )
					spawnflags = "1"
					origin = Vector( -6.15229, 23.321, 19.2375 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "Admin_case_car_colorPickRandom0-1"
						}
					}
				}
			}
			Admin_case_car_color = 
			{
				SpawnInfo =
				{
					classname = "logic_case"
					angles = Vector( -0, -60, 0 )
					Case01 = "1"
					Case02 = "2"
					Case03 = "3"
					Case04 = "4"
					targetname = "Admin_case_car_color"
					origin = Vector( -6.14959, 7.32571, 19.2375 )
					connections =
					{
						OnCase04 =
						{
							cmd1 = "Admin_caralarm_car1Color153 65 290-1"
						}
						OnCase02 =
						{
							cmd1 = "Admin_caralarm_car1Color182 122 680-1"
						}
						OnCase01 =
						{
							cmd1 = "Admin_caralarm_car1Color182 92 680-1"
						}
						OnCase03 =
						{
							cmd1 = "Admin_caralarm_car1Color114 80 520-1"
						}
					}
				}
			}
			Admin_carchirp1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					angles = Vector( -0, -60, 0 )
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "Car.Alarm.Chirp2"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "4000"
					SourceEntityName = "Admin_caralarm_car1"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "Admin_carchirp1"
					volstart = "0"
					origin = Vector( -30.1456, 7.3234, 18.3265 )
				}
			}
			Admin_alarmtimer1 = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					angles = Vector( -0, -60, 0 )
					RefireTime = ".75"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "Admin_alarmtimer1"
					UseRandomTime = "0"
					origin = Vector( -6.14716, -15.2501, 19.2375 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "Admin_caralarm_light1ShowSprite0-1"
							cmd2 = "Admin_caralarm_light1HideSprite0.5-1"
							cmd3 = "Admin_caralarm_light1HideSprite0.5-1"
							cmd4 = "Admin_caralarm_light1ShowSprite0-1"
							cmd5 = "Admin_caralarm_headlights1LightOff0.5-1"
							cmd6 = "Admin_caralarm_headlights1LightOn0-1"
						}
					}
				}
			}
			Admin_caralarm_car1 = 
			{
				SpawnInfo =
				{
					classname = "prop_car_alarm"
					angles = Vector( 0, 0, 0 )
					body = "0"
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "2250"
					fademindist = "2000"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					maxdxlevel = "0"
					mindxlevel = "0"
					minhealthdmg = "0"
					model = "models/props_vehicles/cara_95sedan.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "138 37 9"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "256"
					targetname = "Admin_caralarm_car1"
					origin = Vector( 2.12022, -1.35055, -92.3927 )
					connections =
					{
						OnCarAlarmStart =
						{
							cmd1 = "Admin_alarmtimer1Enable0-1"
							cmd2 = "Admin_caralarm1PlaySound0-1"
							cmd3 = "Admin_caralarm_glass1Disable0-1"
							cmd4 = "Admin_caralarm_glass1_offEnable0-1"
						}
						OnCarAlarmChirpStart =
						{
							cmd1 = "Admin_carchirp1PlaySound0.2-1"
							cmd2 = "Admin_caralarm_light1ShowSprite0.2-1"
						}
						OnCarAlarmEnd =
						{
							cmd1 = "Admin_alarmtimer1Disable0-1"
							cmd2 = "Admin_caralarm1StopSound0-1"
							cmd3 = "Admin_relay_caralarm_offTrigger0-1"
							cmd4 = "Admin_caralarm_light1HideSprite0-1"
							cmd5 = "Admin_caralarm_headlights1LightOff0-1"
							cmd6 = "Admin_caralarm_game_eventKill0-1"
							cmd7 = "Admin_remark_caralarmKill0-1"
						}
						OnCarAlarmChirpEnd =
						{
							cmd1 = "Admin_caralarm_light1HideSprite0.7-1"
						}
					}
				}
			}
			Admin_caralarm_glass1 = 
			{
				SpawnInfo =
				{
					classname = "prop_car_glass"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					maxdxlevel = "0"
					MinAnimTime = "5"
					mindxlevel = "0"
					model = "models/props_vehicles/cara_95sedan_glass_alarm.mdl"
					parentname = "Admin_caralarm_car1"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "Admin_caralarm_glass1"
					origin = Vector( 2.12022, -1.35055, -92.3927 )
				}
			}
			Admin_caralarm_headlights1 = 
			{
				SpawnInfo =
				{
					classname = "beam_spotlight"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					HDRColorScale = ".5"
					maxspeed = "100"
					parentname = "Admin_caralarm_car1"
					renderamt = "150"
					rendercolor = "252 243 226"
					rendermode = "5"
					spawnflags = "2"
					spotlightlength = "256"
					spotlightwidth = "32"
					targetname = "Admin_caralarm_headlights1"
					origin = Vector( 102.928, -30.5469, -62.7867 )
				}
			}
			Admin_caralarm_light1 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					angles = Vector( -0, -60, 0 )
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "5"
					HDRColorScale = "0.7"
					model = "sprites/glow.vmt"
					parentname = "Admin_caralarm_car1"
					renderamt = "255"
					rendercolor = "224 162 44"
					renderfx = "0"
					rendermode = "9"
					scale = ".5"
					spawnflags = "0"
					targetname = "Admin_caralarm_light1"
					origin = Vector( 98.942, -39.5503, -63.4347 )
				}
			}
			Admin_caralarm_light11 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					angles = Vector( -0, -60, 0 )
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "5"
					HDRColorScale = "0.7"
					model = "sprites/glow.vmt"
					parentname = "Admin_caralarm_car1"
					renderamt = "255"
					rendercolor = "224 162 44"
					renderfx = "0"
					rendermode = "9"
					scale = ".5"
					spawnflags = "0"
					targetname = "Admin_caralarm_light1"
					origin = Vector( 98.9492, 37.4422, -63.4657 )
				}
			}
			Admin_caralarm_headlights11 = 
			{
				SpawnInfo =
				{
					classname = "beam_spotlight"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					HDRColorScale = ".5"
					maxspeed = "100"
					parentname = "Admin_caralarm_car1"
					renderamt = "150"
					rendercolor = "252 243 226"
					rendermode = "5"
					spawnflags = "2"
					spotlightlength = "256"
					spotlightwidth = "32"
					targetname = "Admin_caralarm_headlights1"
					origin = Vector( 102.928, 27.4536, -62.7727 )
				}
			}
			Admin_caralarm_light12 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					angles = Vector( -0, -60, 0 )
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "5"
					HDRColorScale = "0.7"
					model = "sprites/glow.vmt"
					parentname = "Admin_caralarm_car1"
					renderamt = "255"
					rendercolor = "255 13 19"
					renderfx = "0"
					rendermode = "9"
					scale = ".5"
					spawnflags = "0"
					targetname = "Admin_caralarm_light1"
					origin = Vector( -104.608, 26.2513, -61.2967 )
				}
			}
			Admin_caralarm_light13 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					angles = Vector( -0, -60, 0 )
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "5"
					HDRColorScale = "0.7"
					model = "sprites/glow.vmt"
					parentname = "Admin_caralarm_car1"
					renderamt = "255"
					rendercolor = "255 13 19"
					renderfx = "0"
					rendermode = "9"
					scale = ".5"
					spawnflags = "0"
					targetname = "Admin_caralarm_light1"
					origin = Vector( -103.809, -30.445, -61.2977 )
				}
			}
			Admin_remark_caralarm = 
			{
				SpawnInfo =
				{
					classname = "info_remarkable"
					angles = Vector( -0, -60, 0 )
					contextsubject = "remark_caralarm"
					origin = Vector( -10.14, -8.68, -4.76 )
					targetname = "Admin_remark_caralarm"
				}
			}
			Admin_caralarm_glass1_off = 
			{
				SpawnInfo =
				{
					classname = "prop_car_glass"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					maxdxlevel = "0"
					MinAnimTime = "5"
					mindxlevel = "0"
					model = "models/props_vehicles/cara_95sedan_glass.mdl"
					parentname = "Admin_caralarm_car1"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "Admin_caralarm_glass1_off"
					origin = Vector( 2.12022, -1.35055, -92.3927 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // AlarmCar

RegisterEntityGroup( "AlarmCar", AlarmCar )
